type: Microsoft.App/containerApps
name: capp-kairos-broker
location: eastus2
properties:
  environmentId: "/subscriptions/28b743cd-805d-4451-ba1f-067df11cbafc/resourceGroups/kairos/providers/Microsoft.App/managedEnvironments/cae-kairos"
  configuration:
    ingress:
      external: true
      targetPort: 8080
      allowInsecure: true
  template:
    containers:
    - image: kairosfinance.azurecr.io/kairos/broker:latest
      name: kairos-broker
      resources:
        cpu: 1
        memory: 2Gi
      probes:
      - type: Liveness
        httpGet:
          path: "/health/live"
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 30
      - type: Readiness
        httpGet:
          path: "/health/ready"
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 60
      env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Staging
      - name: AZURE_TENANT_ID
        value: 9a2a8091-ab6f-4a37-92ee-0163472de920
      - name: AZURE_CLIENT_ID
        secretRef: sp-client-id
      - name: AZURE_CLIENT_SECRET
        secretRef: sp-client-secret

    scale:
      minReplicas: 0
      maxReplicas: 5